version: 0.2

phases:
  build:
    commands:
      - mkdir -p output
      - cp -r www/* output/  

artifacts:
  files:
    - "**/*" 
  discard-paths: no
  base-directory: output
  name: BuildArtifact
