version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm ci
      - npx playwright install

  build:
    commands:
      - npm run build  # next.config.js must include `output: 'export'`

  post_build:
    commands:
      - echo "Running Playwright smoke tests..."
      - npx playwright test

artifacts:
  base-directory: frontend/out  # This is where `next export` puts static site
  files:
    - "**/*"
  discard-paths: no
  name: BuildArtifact
