version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm ci

  build:
    commands:
      - npm run build  # next.config.js must include `output: 'export'`

artifacts:
  base-directory: frontend/out  # This is where `next export` puts static site
  files:
    - "**/*"
  discard-paths: no
  name: BuildArtifact
  